#!/bin/sh

print_usage()
{
    echo "usage: pundun-docker COMMAND\n\rCOMMAND:\n\r\t build REPO TAG | run REPO TAG | stop REPO TAG | rm REPO TAG | attach REPO TAG\n\rREPO:\n\r\t pundun-ready | pundun-master\n\rTAG:\n\r\t ubuntu-16.04 | centos-6.7"
}

if [ -z $2 ] || [ -z $3 ]; then
    print_usage
else
    case $1 in
	"run")
	    docker run -d -P --name $2-$3 pundunlabs/$2:$3
	    ;;
	"stop")
	    docker stop $2-$3
	    ;;
	"rm")
	    docker rm $2-$3
	    ;;
	"build")
	    (cd $2/$3; docker build -t pundunlabs/$2:$3 .)
	    ;;
	"attach")
	    ipport=`docker port $2-$3 22`
	    port=`echo ${ipport##*:}`
	    ssh root@0.0.0.0 -p $port -t '/bin/bash'
	    ;;
	*)
	    print_usage
    esac
fi
