#!/bin/sh

print_usage()
{
    echo "usage: pundun-container COMMAND\n\rCOMMAND:\n\r\t build [TAG] | start [TAG] | stop | rm | attach\n\rTAG:\n\r\t ubuntu-16.04 | centos-6.7"
}

case $1 in
    "start")
	if [ -z $2 ]; then
	    print_usage
	else
	    docker run -d -P --name pundun-1.0.0 pundunlabs/pundun:$2
	fi
	;;
    "stop")
	docker stop pundun-1.0.0
	;;
    "rm")
	docker rm pundun-1.0.0
	;;
    "build")
	if [ -z $2 ]; then
	    print_usage
	else
	    (cd $2; docker build -t pundunlabs/pundun:centos-6.7 .)
	fi
	;;
    "attach")
	ipport=`docker port pundun-1.0.0 22`
	port=`echo ${ipport##*:}`
	ssh pundun@0.0.0.0 -p $port -t '/bin/bash'
	;;
    *)
	print_usage
esac
